### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by AvishaiAt** [AvihaiV/Tene-Yerushalmi#2]
https://github.com/AvihaiV/Tene-Yerushalmi/wiki/srs

**Comment by robi-y** [comment]
- Missing actors and stakeholder
- Separate UC of uploading and viewing contact
- think of the concurrent posting
- uploading images?

**Comment by HodayaAt** [comment]
העלאתי קובץ חדש, בוצעו בו שינויים. @robi-y  @kob-e
