### ISSUE TITLE
Help to install angularFire2

### ISSUE THREAD

**Issue by HodayaAt** [AvihaiV/Tene-Yerushalmi#21]
אנחנו לא מצליחים להתקין את האנגולרפייר2, ולכן אין אפשרות לשייך את המסד נתונים של פיירבייס.
נשמח לעזרה דחופה!!

@kob-e @robi-y

**Comment by robi-y** [comment]
תתאמו פגישה ליום שלישי לתרגול

2017-05-11 17:30 GMT+03:00 Hodaya Attia <notifications@github.com>:
