### ISSUE TITLE
Exercise 2 - Inception : Feedback

### ISSUE THREAD

**Issue by kob-e** [AvihaiV/Tene-Yerushalmi#3]
- לא תייגתם אותי בissue שפתחתם
- חסר שונות בין חברי הצוות
תייגו אותי אחרי שתעשו את השינויים

**Comment by karinbe** [comment]
תייגנו אותך ב-ISSUE
השונות של הצוות אכן מופיעה אז איפה הבעיה?

**Comment by kob-e** [comment]
יפה
